version: "3.9"
services:
  api-gateway:
    build: ../../services/api-gateway
    ports:
      - "4000:4000"
  auth-service:
    build: ../../services/auth-service
    ports:
      - "3001:3001"
  task-service:
    build: ../../services/task-service
    ports:
      - "3002:3002"
  realtime-service:
    build: ../../services/realtime-service
    ports:
      - "3003:3003"
  notification-service:
    build: ../../services/notification-service
    ports:
      - "3004:3004"
  file-service:
    build: ../../services/file-service
    ports:
      - "3005:3005"
  analytics-service:
    build: ../../services/analytics-service
    ports:
      - "8000:8000"
